### ISSUE TITLE
alpha on shapes doesn't work properly if there's no background()

### ISSUE THREAD

**Issue by juliendorra** [jonathanperret/paysage#70]
This:
```
void draw() {
fill(0, 128);
rect(200, 100, 100, 100)
}
```
should draw a semi-transparent black square, appearing grey.
It works here : http://processingjs.org/tools/processing-helper.html and http://sketchpad.cc/0ToVURmcxG

On Paysage it appears transparent then rapidly become fully opaque, in a fade.

As a workaround, adding a background() function make it works:
```
void draw() {
background ()
fill(0, 100);
rect(200, 100, 100, 100)
}
```

It might be coming from the new way to handle default backgrounds.

**Comment by jonathanperret** [comment]
Are you sure? Note that running your example code:
```
void draw() {
fill(0, 128);
rect(200, 100, 100, 100)
}
```

In  http://processingjs.org/tools/processing-helper.html or http://sketchpad.cc produces a grey area… because grey is the default background in these environments and you're drawing outside of the default 150x150 bounds 😂 

Try this instead:
```
void draw() {
fill(0, 128);
rect(20, 10, 10, 10)
}
```

And you'll see the "fading" behaviour you're complaining about 😉
